name: novusdata
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_local_notifications: ^17.2.2
  flutter_background_service: ^5.0.10
  logger: ^2.4.0
  connectivity_plus: ^6.0.5
  permission_handler: ^11.3.1
  socket_io_client: ^2.0.3+1
  flutter_riverpod: ^2.5.1
  collection: ^1.18.0
  conduit: ^5.1.3
  workmanager: ^0.5.2
  timezone: ^0.9.4
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  device_info_plus: ^10.1.2



  # HTTP package for making API requests
  http: ^1.2.2

  # Provider package for state management
  provider: ^6.1.2

  # JSON serialization
  json_annotation: ^4.9.0

  # Flutter widgets for displaying charts
  fl_chart: ^0.69.0

  #User Added Device Data to be Stored in MObile Application after first login
  shared_preferences: ^2.3.2
  #12 hour Time Display
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # JSON serialization code generator
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  # Add any assets like images or fonts here
  assets:
    - assets/SplashLogo.png
    - assets/FATRONIC LOGO.png


  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
